name: Building NGINX Container

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  add-ip-whitelist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Cred
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        IPS=(${{ steps.ip.outputs.ipv4 }} )
        echo $IPS

    - name: Add GithubACTION IP addresses to EC2 SG
      run: |
        IPS=(${{ steps.ip.outputs.ipv4 }} )
        echo $IPS
        # Get the existing inbound rules of the EC2 SG    
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.SECURITY_GROUP_ID}} --protocol tcp --port 22 --cidr  $IPS/32 --region ${{ env.AWS_REGION }}
        
    - name: SSH into EC2 instance & deploy Nginx 
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo su
          sudo docker pull nginx:latest
          sudo docker run -itd --name nginx -p 80:80 nginx:latest
          sudo docker ps 
          echo "DEPLOYED" 
          
    - name: Remove GithubAction IP_ADD From AWS_SG
      run: | 
        IPS=(${{ steps.ip.outputs.ipv4 }} )
        echo $IPS
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.SECURITY_GROUP_ID}} --protocol tcp --port 22 --cidr  $IPS/32 --region ${{ env.AWS_REGION }}

