name: Add GitHub Actions IP Whitelist to EC2 SG

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  add-ip-whitelist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        IPS=(${{ steps.ip.outputs.ipv4 }} )
        echo $IPS

    - name: Add IP addresses to EC2 SG
      run: |
        IPS=(${{ steps.ip.outputs.ipv4 }} )
        echo $IPS
        # Get the existing inbound rules of the EC2 SG    
        aws ec2 authorize-security-group-ingress --group-id sg-0f621ddb3a37eb5ac --protocol tcp --port 22 --cidr  $IPS/32 --region ${{ env.AWS_REGION }}
        
       
