name: Add GitHub Actions IP Whitelist to EC2 SG

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  add-ip-whitelist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get GitHub Actions IP addresses
      run: |
        # Get the current GitHub Actions IP addresses
        IPS=($(curl -s https://api.github.com/meta | jq -r '.hooks[].ip'))

    - name: Add IP addresses to EC2 SG
      run: |
        # Get the existing inbound rules of the EC2 SG
        RULES=($(aws ec2 describe-security-groups --group-id  --region ${{ env.AWS_REGION }} | jq '.SecurityGroups[].IpPermissions'))

        # Add the GitHub Actions IP addresses to the EC2 SG
        for IP in "${IPS[@]}"; do
          RULES+=("{\"IpProtocol\":\"tcp\",\"FromPort\":22,\"ToPort\":22,\"IpRanges\":[{\"CidrIp\":\"$IP/32\"}]}")
        done

        aws ec2 authorize-security-group-ingress --group-id sg-0f621ddb3a37eb5ac --ip-permissions "${RULES[@]}" --region ${{ env.AWS_REGION }}
