name: Access AWS EC2 Instance

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  access-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get GitHub Actions IP addresses
      run: |
        # Get the current GitHub Actions IP addresses
        IPS=($(curl -s https://api.github.com/meta | jq -r '.hooks[].ip'))
        
    - name: Install and configure AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        aws configure set default.region ${{ env.AWS_REGION }}

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo su
          sudo docker pull nginx:latest
          sudo docker run -itd --name nginx -p 80:80 nginx:latest
          sudo docker ps 
          echo "DEPLOYED" 
