name: Access AWS EC2 Instance

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  access-ec2:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get runner IP
      run: |
        echo "::set-env name=RUNNER_IP::$(curl -s https://checkip.amazonaws.com)"

    - name: Install and configure AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        aws configure set default.region ${{ env.AWS_REGION }}

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo su
          sudo docker pull nginx:latest
          sudo docker run -itd --name nginx -p 80:80 nginx:latest
          sudo docker ps 
          echo "DEPLOYED" 
